### ISSUE TITLE
Carbon Fiber prices

### ISSUE THREAD

**Issue by Maldark** [zmiguel/Eve-Reactions-Calculator#68]
Hi,
I'm puzzled as to the Carbon Fiber reaction, are the prices off for some reason? 

It's saying that in a 120-cycle it produces 24000 Carbon Fiber worth 42,168,000, but if I look up 24000 Carbon Fiber on Janice or in Jita its worth about double that. The other reactions I've checked are accurate.

https://reactions.coalition.space/composite/simple/57453 for reference

Thanks, and thanks for the site; I just started using it.

**Comment by zmiguel** [comment]
It seems the prices are very outdated on the database. I'm checking why.

**Comment by zmiguel** [comment]
@Maldark somehow the item was removed from the items to update list, should be fixed now. 

Sorry for the delay.

**Comment by Maldark** [comment]
All good, happy to hear that my suspicions were well founded.

Thank you for fixing it!
