### ISSUE TITLE
Floating box covers J space button at the bottom on mobile

### ISSUE THREAD

**Issue by Pixelest** [zmiguel/Eve-Reactions-Calculator#72]
It’s almost impossible to click the button at the bottom when viewing on mobile. The hovering box covers it when scrolled all the way down
![IMG_2509](https://github.com/zmiguel/Eve-Reactions-Calculator/assets/2861198/3f3eacb7-18d0-47d8-9294-25c33c04310b)

**Comment by zmiguel** [comment]
Fixed by #73 
Thanks, @riyashivolkar!
